# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hugo Hammond
title: Postdoctoral Researcher
email: hugo.hammond@vanderbilt.edu

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  hugohammond
linkedin_username: hugo-hammond-aaa14b151
orcid_username: 0000-0003-2411-6924

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.svg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Hugo. I'm a Postdoc at Vanderbilt University in the department of Psychology and Human Development.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Measuring audience immersion
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme

        description: | # this will include new lines to allow paragraphs
          ![Correlation between audience heart rate and retrospective engagement](/modern-resume-theme/images/heart_rate_isc.jpg "Heart rate")
          Here, we show that secondary-task reaction times, and intersubject correlation of heart rate, relate to self-reported engagement scores across several short clips.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Bristol
        caption: 2015 - 2018
        sub_title: **BSc**, Psychological Science
        description: | # this will include new lines to allow paragraphs
          Add a description...
        title: University of Bristol
        caption: 2018 - 2022
        sub_title: **PhD**, Psychological Science  



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
